apiVersion: v1
kind: Secret
metadata:
  name: oracle-db-secrets
type: Opaque
stringData:
  database-password: "${ORACLE_DB_PASSWORD}"
  jwt: "${JWT_SECRET}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db-deployment
  labels:
    app: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
        - name: oracle-db-container
          image: container-registry.oracle.com/database/free:latest
          ports:
            - containerPort: 1521
          env:
            - name: ORACLE_PWD
              valueFrom:
                secretKeyRef:
                  name: oracle-db-secrets
                  key: database-password

---
apiVersion: v1
kind: Service
metadata:
  name: oracle-db-service
spec:
  type: ClusterIP
  selector:
    app: oracle-db
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinesuggest-deployment
  labels:
    app: cinesuggest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cinesuggest
  template:
    metadata:
      labels:
        app: cinesuggest
    spec:
      containers:
        - name: cinesuggest-container
          image: vitoresbr/cinesuggest:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:oracle:thin:@oracle-db-service:1521/FREEPDB1"
            - name: SPRING_DATASOURCE_USERNAME
              value: "SYSTEM"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-db-secrets
                  key: database-password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "oracle.jdbc.OracleDriver"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "create"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oracle-db-secrets
                  key: jwt
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: "org.hibernate.dialect.OracleDialect"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: cinesuggest-service
spec:
  type: ClusterIP
  selector:
    app: cinesuggest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinesuggest-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api-cinesuggest.evitorsilva.site
      secretName: cinesuggest-tls-secret
  rules:
    - host: api-cinesuggest.evitorsilva.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cinesuggest-service
                port:
                  number: 80

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ceja.vitorgabriel.e.silva@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik