apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinesuggest-deployment
  labels:
    app: cinesuggest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cinesuggest-api
  template:
    metadata:
      labels:
        app: cinesuggest-api
    spec:
      containers:
        - name: cinesuggest-container
          image: vitoresbr/cinesuggest:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:oracle:thin:adb.sa-saopaulo-1.oraclecloud.com:1521/FREEPDB1"
            - name: SPRING_DATASOURCE_USERNAME
              value: "cinesuggest_user"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-db-secrets
                  key: database-password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "oracle.jdbc.OracleDriver"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
              value: "CINESUGGEST_USER"

---
apiVersion: v1
kind: Service
metadata:
  name: cinesuggest-service-api
spec:
  type: ClusterIP
  selector:
    app: cinesuggest-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080