spring.application.name="CineSuggest"
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//127.0.0.1:1521/FREE
spring.datasource.username=system
spring.datasource.password=senhadificil
api.security.token.secret=SenhaDFFFDoToken
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

