spring.application.name="CineSuggest"
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=system
spring.datasource.password=senhadificil
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

