spring.application.name="CineSuggest"

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@//127.0.0.1:1521/FREEPDB1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cinesuggest_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.synonyms=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.default_schema=CINESUGGEST_USER
spring.flyway.enabled=true

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

jwt.secret=${JWT_SECRET:SenhaDFFFDoToken}