CREATE TABLE CATALOG_MEDIA (
                               ID NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE CATALOG_MEDIA_CONTENT (
                                       CATALOG_ENTITY_ID NUMBER(19, 0) NOT NULL,
                                       CONTENT_ID NUMBER(19, 0) NOT NULL,

                                       CONSTRAINT PK_CATALOG_MEDIA_CONTENT PRIMARY KEY (CATALOG_ENTITY_ID, CONTENT_ID),

                                       CONSTRAINT FK_CMC_CATALOG FOREIGN KEY (CATALOG_ENTITY_ID)
                                           REFERENCES CATALOG_MEDIA (ID) ON DELETE CASCADE,

                                       CONSTRAINT FK_CMC_MEDIA FOREIGN KEY (CONTENT_ID)
                                           REFERENCES MEDIAS (ID) ON DELETE CASCADE
);