name: Java CI/CD with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.14.4'

      - name: Build with Gradle Wrapper
        run: chmod +x gradlew && ./gradlew build -x test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (Multi-arch)
        uses: docker/build-push-action@v5
        with:
          file: ./docker/Dockerfile
          context: .
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cinesuggest:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cinesuggest:${{ github.sha }}

      - name: Replace image tag in deployment template
        run: |
          sed -i 's|cinesuggest:latest|cinesuggest:${{ github.sha }}|g' deploy.yaml

      - name: Copy deploy.yaml to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "deploy.yaml"
          target: "~/.k3s_deploys/${{ github.event.repository.name }}/"

      - name: Deploy on Server Ubuntu (K3s)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
                    k3s kubectl --kubeconfig=/var/www/.kube/config create secret generic oracle-db-secrets \
                      --from-literal=database-password="${{ secrets.ORACLE_DB_PASSWORD }}" \
                      --from-literal=jwt=${{ secrets.JWT }}"
            
                    k3s kubectl --kubeconfig=/var/www/.kube/config apply -f ~/.k3s_deploys/${{ github.event.repository.name }}/deploy.yaml
            
                    k3s kubectl --kubeconfig=/var/www/.kube/config rollout restart deployment/cinesuggest-deployment || true